# Generated by Django 5.1.2 on 2025-01-24 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0002_alter_alumni_options_alter_teacher_options_and_more'),
        ('socialnetwork', '0003_alter_postimage_post'),
    ]

    operations = [
    ]
