# Generated by Django 5.1.2 on 2025-01-25 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0004_merge_20250124_1735'),
        ('socialnetwork', '0004_merge_20250124_1757'),
    ]

    operations = [
    ]
