# Generated by Django 5.1.2 on 2025-01-25 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0005_merge_20250125_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyoption',
            name='users',
        ),
        migrations.CreateModel(
            name='UserSurveyOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialnetwork.surveyoption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'survey_option')},
            },
        ),
    ]
