# Generated by Django 5.1.2 on 2025-01-25 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0006_remove_surveyoption_users_usersurveyoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyquestion',
            name='survey_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='socialnetwork.surveypost'),
        ),
        migrations.CreateModel(
            name='SurveyDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=dict)),
                ('drafted_at', models.DateTimeField(auto_now=True)),
                ('survey_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='socialnetwork.surveypost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('survey_post', 'user')},
            },
        ),
    ]
