# Generated by Django 5.1.2 on 2025-01-25 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0007_alter_surveyquestion_survey_post_surveydraft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyoption',
            name='survey_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='socialnetwork.surveyquestion'),
        ),
    ]
