# Generated by Django 5.1.2 on 2025-02-07 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0008_alter_surveyoption_survey_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id']},
        ),
    ]
